### PR TITLE
build.sh dependency fix

### PR DESCRIPTION
**Pull request by AndySchroder**
add zip dependency in setup-debian.sh for build.sh

helps resolve https://github.com/estkme-group/lpac/issues/75

### CODE REVIEW

**Comment by AndySchroder** [comment]
Please close https://github.com/estkme-group/lpac/pull/109 first. It will be much easier to see how compact this change is.

**Comment by damonto** [comment]
You should checkout a new branch on the branch of main.

**Comment by AndySchroder** [comment]
> You should checkout a new branch on the branch of main.

done

**Comment by AndySchroder** [comment]
Any reason why you don't want to merge this?

**Comment by BeRealQueally** [comment]
close as https://github.com/estkme-group/lpac/pull/111#issuecomment-2138686705

**Pull request merged**
