### PR TITLE
debian: remove libc dependency, standardize package output file name, fix compilation instructions (fixes issues 75 & 105 and prepares to fix issue #99)

### PR DESCRIPTION
**Pull request by AndySchroder**
debian package: remove libc dependency and standardize output file name (fixes issue #105 and prepares to fix issue #99)

### CODE REVIEW

**Comment by AndySchroder** [comment]
Please see issue #105. I don't think libc is required, but would like you to check.

**Comment by AndySchroder** [comment]
Also added 49f2fd53bcb324fe8968efde976c7791132260c9, "fix and clean up debian compilation instructions and resolve issue #75".

**Comment by CoelacanthusHex** [comment]
If you want to fix multi issue with different modification, please open multi Pull Request instead of one. One PR should only do one thing.

**Review by septs — CHANGES_REQUESTED** [review]
please split into multiple pull requests

**Comment by AndySchroder** [comment]
This pull request is replaced by

- https://github.com/estkme-group/lpac/pull/108
- https://github.com/estkme-group/lpac/pull/109
- https://github.com/estkme-group/lpac/pull/110
- https://github.com/estkme-group/lpac/pull/111

**Pull request closed without merging**
